apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress
spec:
  type: NodePort     ## type du service
  ports:
    - targetPort: 80              ## port exposé en interne
      port: 80
      nodePort: 30080
  selector:
    app: wordpress


